build:lscsky50-d:
  stage: build
  tags:
    - skylake
  only:
    - molecular_lines_beta
  script:
    - make clean
    - make
  artifacts:
    paths:
      - ./*.so
      - ./*.a
      - ./*.mod
      - ./*.o

test:lscsky50-d:
  stage: test
  tags:
    - skylake
  only:
    - molecular_lines_beta
  script:
    - make test
  dependencies:
    - build:lscsky50-d
