build:lscsky50:
  stage: build
  tags:
    - lscsky50
  only:
    - modular_lines
  script:
    - make clean
    - make
  artifacts:
    paths:
      - ./*.so
      - ./*.a
      - ./*.mod

test:lscsky50:
  stage: test
  tags:
    - lscsky50
  only:
    - modular_lines
  script:
    - make test
  dependencies:
    - build:lscsky50
