build:lscgpu50-d:
  stage: build
  tags:
    - gpudevbox
  script:
    - source /opt/lmod/lmod/init/bash
    - module load cuda/9.1
    - module load gcc/7.3.0
    - autoreconf --install
    - ./configure --prefix /home/Raymond.Menzel/local/molecular_lines
                  --enable-fortran-bindings --enable-cuda CC=nvcc
                  CFLAGS="-g -O2 -fopenmp" NVCCFLAGS="-ccbin gcc"
                  FC=gfortran FFLAGS="-g -O2 -fopenmp" LDFLAGS="-fopenmp"
                  PYTHON=/home/Raymond.Menzel/packages/Python-3.5.5/bin/python3
    - make
  artifacts:
    untracked: true
    expire_in: 5 mins


deploy:lscgpu50-d:
  stage: deploy
  tags:
    - gpudevbox
  script:
    - make install
  dependencies:
    - build:lscgpu50-d


build:lscsky50-d:
  stage: build
  tags:
    - skylake
  script:
    - source /opt/lmod/lmod/init/bash
    - module load gcc/7.2.0
    - autoreconf --install
    - ./configure --prefix /home/Raymond.Menzel/local/molecular_lines
                  --enable-fortran-bindings CC=gcc CFLAGS="-g -O2 -fopenmp"
                  FC=gfortran FFLAGS="-g -O2 -fopenmp" LDFLAGS="-fopenmp"
                  PYTHON=/home/Raymond.Menzel/local/bin/python3
    - make
  artifacts:
    untracked: true
    expire_in: 5 mins


deploy:lscsky50-d:
  stage: deploy
  tags:
    - skylake
  script:
    - make install
  dependencies:
    - build:lscsky50-d
