#!/bin/bash

function run {
    printf "Running test $1\n"
    ./$1 $2
    if [ "$?" -eq 0 ]; then
        printf "Passed.\n"
    else
        printf "Failed.\n" && exit 1
    fi
}

declare -a tests=("example.x" "example_f.x" "example_fhl.x")

#Run some tests on the host.
printf "Running tests on the host CPU.\n"
for i in ${tests[@]}; do
    run $i --host
done
printf "All host tests passed.\n"

if [ "$1" != "--host" ]; then
    #Look for some gpus.
    num_gpus=`nvidia-smi --list-gpus | wc -l`
    if [ "$?" -eq 0 ] && [ "$num_gpus" -gt 0 ]; then
        #Run some tests on GPUs.
        printf "Found $num_gpus GPUs.  Running tests on the GPUs.\n"
        for i in ${tests[@]}; do
            run $i $num_gpus
        done
        printf "All GPU tests passed.\n"
    else
        printf "No GPUs found.\n"
    fi
fi
printf "All tests passed.\n"
exit 0
