CC = cc
NVCC = nvcc
#CFLAGS = '-g -Wall -Wextra -pedantic -std=c99'
CFLAGS = '-g'
CLIBS = -lnetcdf -lhdf5 -lm
NVCCFLAGS = --compiler-options ${CFLAGS} -g
NVCCLDFLAGS = --compiler-options '-shared -fPIC'

#CFLAGS = -g -Wall -Wextra -Werror -pedantic -std=c99
OBJ = grtcode.o write_output.o launch.o lw_flux.o output_fields.o eval_profile.o RfmVoigtFuncs.o IdaVoigtFuncs.o GaussianFuncs.o eval_Snn_correction.o eval_pShift.o eval_gamma.o LorentzFuncs.o pre_eval_Snn.o line_shape_utils.o GasProps.o integrate_layer.o TIPS_2011.o continuum.o parseHITRANfile.o input_fields.o model_fields.o arguments.o molecules.o cudaHelpers.o utils.o constants.o
EXECUTABLE = grtcode.x

INCLUDE = 
LDFLAGS =
LIBS = -lnetcdf -lhdf5 -lm
RPATH =

all: ${EXECUTABLE}

${EXECUTABLE}: ${OBJ}
	${NVCC} ${NVCCFLAGS} -o $@ $^ ${CLIBS}

%.o:%.c
	${NVCC} -x cu -dc ${NVCCLDFLAGS} ${NVCCFLAGS} -o $@ -c $<

%.o: %.cu
	${NVCC} -x cu -dc ${NVCCLDFLAGS} ${NVCCFLAGS} -o $@ -c $<

clean:
	rm -f *.o *.x
